# Generated by Django 5.1.3 on 2024-11-26 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study', models.CharField(help_text='Field of study', max_length=255)),
                ('hobby', models.CharField(help_text="User's hobby", max_length=255)),
                ('skill', models.CharField(help_text="User's skill", max_length=255)),
                ('job', models.CharField(help_text='Dream job', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Timestamp of the profile creation')),
            ],
        ),
    ]
